name: Publikuj na ftp.zspw.pl
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
jobs:
  build:
    # Job name is Greeting
    name: Publish  covid19 app
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: ftp auth
        #uses: actions/hello-world-javascript-action@v1
        #with:
        #  who-to-greet: 'Mona the Octocat'
        #id: hello
        run: echo 'Test ok'
      # This step prints an output (time) from the previous step's action.
      #- name: Echo the greeting's time
      #  run: echo 'The time was ${{ steps.hello.outputs.time }}.'
