name: Publikuj na ftp.zspw.pl
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
jobs:
  build:
    # Job name is covid19 app
    name: Publish covid19 app
    # This job runs on Linux
    runs-on: centos-latest
    steps:
      - name: ftp auth
        run: echo 'Auth [OK]'
      #- name: Echo the greeting's time
      - name: ftp deploy
        run: echo 'Deploy [OK]'
