name: Publikuj na ftp.zspw.pl
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
jobs:
  build:
    # Job name is Greeting
    name: Publish covid19 app
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: zspw.pl
          FTP_USERNAME: covid19
          FTP_PASSWORD: Q@wertyuiop
          #LOCAL_DIR: covid-19-app
          REMOTE_DIR: public_html 
          #ARGS: --delete
